Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "docker-host"
  config.vm.provision "docker"
  config.vm.network :forwarded_port, guest: 80, host: 4567
  config.vm.synced_folder ".", "/home/vagrant/sync", disabled: true
end