
 - name: Install packages
   yum: pkg={{item}} state=installed
   with_items:
     - httpd
     - php
     - php-mysql
     - php-gd
     - git
     - haproxy
     - openssl-delevel
     - mariadb-server
     - php-xml
     - mariadb
     - mediawiki*

 - name: Create Directory For HaProxy
   file: path=/run/haproxy state=directory
   file: path=/var/lib/haproxy state=directory
   file: path=/var/lib/haproxy/stats state=file 

